# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Push image of ServiceA to DockerHub

on:
  push:
    branches: ["main"]
    conditions: contains(github.event.head_commit.message, "[ci build]")
  pull_request:
    branches: ["main"]
    conditions: contains(github.event.head_commit.message, "[ci build]")

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check commit message prefix
        run: |
          if [[ "${{ github.event.head_commit.message }}" != *"[ci build]"* ]]; then
            echo "Commit message does not contain the required prefix. Skipping workflow."
            exit 0
          fi

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests
      # - name: Test with Maven
      #   run: mvn test && mvn package
      # - name: Build Jar file
      #   run: mkdir staging && cp target/*.jar staging
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Package
      #     path: staging
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ductram/test_service_a:latest
          # image: ductram/project_ab
          # tags: latest
          # registry: docker.io
          # dockerfile: Dockerfile
          # username: ${{ secrets.DOCKER_USERNAME }}
          # password: ${{ secrets.DOCKER_TOKEN }}
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
