# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      env:
        description: "environment"
        required: true
        type: choice
        options: [dev, stag, prod]
        default: dev

      cluster-name-dev:
        description: "DEV cluster selection to deploy the app"
        required: true
        type: choice
        options:
          - blue
          - green
        default: "blue"

      cluster-name-npr:
        description: "NON-PROD clusters to have the app deployed to"
        required: true
        type: choice
        options:
          - blue
          - green
        default: "blue"
        
      cluster-name-prd:
        description: "PROD clusters to have the app deployed to"
        required: true
        type: choice
        options:
          - blue
          - green
        default: "blue"

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[ci build]')
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
